### ISSUE TITLE
Model run not marked as complete

### ISSUE THREAD

**Issue by Sybrand** [bcgov/wps#494]
**Describe the Bug**
Under certain conditions, model runs are reported as not not marked as complete, see log output - note that the date for the url date (17th) not match the run it's trying to mark (18th)
This may be causing model runs to be missed.

LOG:

2020-09-18 02:21:55,670 - __main__ - INFO - file already processed https://dd.weather.gc.ca/model_gem_global/15km/grib2/lat_lon/12/240/CMC_glb_TMP_TGL_2_latlon.15x.15_2020091712_P240.grib2 
2020-09-18 02:21:55,671 - __main__ - INFO - file already processed https://dd.weather.gc.ca/model_gem_global/15km/grib2/lat_lon/12/240/CMC_glb_RH_TGL_2_latlon.15x.15_2020091712_P240.grib2 
2020-09-18 02:21:55,681 - __main__ - INFO - we have processed 162/162 files
2020-09-18 02:21:55,681 - __main__ - INFO - GDPS model run 12 completed with SUCCESS
2020-09-18 02:21:55,694 - __main__ - INFO - prediction_model:id:1, name:Global Deterministic Prediction System, abbreviation:GDPS, projection:latlon.15x.15, prediction_run_timestamp:2020-09-18 12:00:00+00:00
2020-09-18 02:21:55,694 - app.db.crud - INFO - get prediction run for 2020-09-18 12:00:00+00:00
2020-09-18 02:21:55,719 - __main__ - ERROR - unexpected exception processing GDPS model run 12
Traceback (most recent call last):
  File "/app/app/models/env_canada.py", line 298, in process
    self.process_model_run(hour)
  File "/app/app/models/env_canada.py", line 291, in process_model_run
    mark_prediction_model_run_processed(
  File "/app/app/models/env_canada.py", line 196, in mark_prediction_model_run_processed
    prediction_run.complete = True
AttributeError: 'NoneType' object has no attribute 'complete'

**Comment by Sybrand** [comment]
Another example of it failing, and resulting in the container restarting and trying again:

2020-10-01 00:19:49,434 - __main__ - INFO - file already processed https://dd.weather.gc.ca/model_gem_global/15km/grib2/lat_lon/12/240/CMC_glb_TMP_TGL_2_latlon.15x.15_2020093012_P240.grib2 
2020-10-01 00:19:49,435 - __main__ - INFO - file already processed https://dd.weather.gc.ca/model_gem_global/15km/grib2/lat_lon/12/240/CMC_glb_RH_TGL_2_latlon.15x.15_2020093012_P240.grib2 
2020-10-01 00:19:49,453 - __main__ - INFO - we have processed 162/162 files
2020-10-01 00:19:49,453 - __main__ - INFO - GDPS model run 12 completed with SUCCESS
2020-10-01 00:19:49,474 - __main__ - INFO - prediction_model:id:1, name:Global Deterministic Prediction System, abbreviation:GDPS, projection:latlon.15x.15, prediction_run_timestamp:2020-10-01 12:00:00+00:00
2020-10-01 00:19:49,474 - app.db.crud - INFO - get prediction run for 2020-10-01 12:00:00+00:00
2020-10-01 00:19:49,502 - __main__ - ERROR - unexpected exception processing GDPS model run 12
Traceback (most recent call last):
  File "/app/app/models/env_canada.py", line 299, in process
    self.process_model_run(hour)
  File "/app/app/models/env_canada.py", line 292, in process_model_run
    mark_prediction_model_run_processed(
  File "/app/app/models/env_canada.py", line 196, in mark_prediction_model_run_processed
    prediction_run.complete = True
AttributeError: 'NoneType' object has no attribute 'complete'
2020-10-01 00:19:49,506 - app.config - WARNING - Expected environment variable (USE_WFWX) not set.
2020-10-01 00:19:49,506 - app.wildfire_one - INFO - USE_WFWX = False
2020-10-01 00:19:49,506 - app.stations - INFO - Using pre-generated json to retrieve station list
2020-10-01 00:19:49,545 - __main__ - INFO - 0 downloaded, 0 processed in total, took 46.4 seconds
2020-10-01 00:19:49,545 - __main__ - WARNING - completed processing with some exceptions
